
seed: 42

data:
  nd_spectra_path: null   # e.g., data/sample/nd_spectra.npy
  fd_targets_path: null   # optional; else synthetic
  n_sections: 8
  n_bins: 60
  d_embed: 64
  batch_size: 32
  steps_per_epoch: 32     # for synthetic

model:
  temperature: 1.0
  dropout_rate: 0.1

train:
  epochs: 3
  lr: 1e-3
  early_stopping:
    patience: 5
    min_delta: 1e-4

out:
  model_dir: models
  model_name: NOvA_NN.keras
  log_dir: logs
